// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: proto/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FamilyCookingServiceClient is the client API for FamilyCookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FamilyCookingServiceClient interface {
	SayHello(ctx context.Context, in *SayHelloReq, opts ...grpc.CallOption) (*SayHelloRes, error)
}

type familyCookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFamilyCookingServiceClient(cc grpc.ClientConnInterface) FamilyCookingServiceClient {
	return &familyCookingServiceClient{cc}
}

func (c *familyCookingServiceClient) SayHello(ctx context.Context, in *SayHelloReq, opts ...grpc.CallOption) (*SayHelloRes, error) {
	out := new(SayHelloRes)
	err := c.cc.Invoke(ctx, "/FamilyCookingService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FamilyCookingServiceServer is the server API for FamilyCookingService service.
// All implementations must embed UnimplementedFamilyCookingServiceServer
// for forward compatibility
type FamilyCookingServiceServer interface {
	SayHello(context.Context, *SayHelloReq) (*SayHelloRes, error)
	mustEmbedUnimplementedFamilyCookingServiceServer()
}

// UnimplementedFamilyCookingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFamilyCookingServiceServer struct {
}

func (UnimplementedFamilyCookingServiceServer) SayHello(context.Context, *SayHelloReq) (*SayHelloRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedFamilyCookingServiceServer) mustEmbedUnimplementedFamilyCookingServiceServer() {}

// UnsafeFamilyCookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FamilyCookingServiceServer will
// result in compilation errors.
type UnsafeFamilyCookingServiceServer interface {
	mustEmbedUnimplementedFamilyCookingServiceServer()
}

func RegisterFamilyCookingServiceServer(s grpc.ServiceRegistrar, srv FamilyCookingServiceServer) {
	s.RegisterService(&FamilyCookingService_ServiceDesc, srv)
}

func _FamilyCookingService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyCookingServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FamilyCookingService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyCookingServiceServer).SayHello(ctx, req.(*SayHelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FamilyCookingService_ServiceDesc is the grpc.ServiceDesc for FamilyCookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FamilyCookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FamilyCookingService",
	HandlerType: (*FamilyCookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _FamilyCookingService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
